### ISSUE TITLE
TimeseriesAPI: Support more/arbitrary metadata

### ISSUE THREAD

**Issue by epa095** [equinor/OmniaPlant#3]
**Is your feature request related to a problem? Please describe.**
I want to make a timeseries in the timeseries API (e.g. the output of a machine learning algorithm), and I know some interesting things about the timeseries which I wants to store in the metadata of the generated timeseries object. Today it seems like I would have to encode all my interesting data into the "description" field, but this can get quite messy.

**Describe the solution you'd like**
I have 3 different alternatives in sinking order of difficulty and awesomeness:

1.  Allow me to add arbitrary metadatafields which will all be searchable.
2. Allow me to add arbitrary metadatafields which will not be searchable, but I will see them when I get the timeseries object. 
3. Add a few more hardcoded metadata fields which I can use for my own purpose. In this alternative maybe even give them lame names like "Info1", "Info2" etc to indicate that they have no semantic meaning. 

For us point 1 is overkill, but clearly the coolest. We will be happy if we get any of them. 

**Describe alternatives you've considered**
Encode the info into the description field. But this makes it hard to use programmatically.

**Comment by ssorenes** [comment]
Thanks for the contribution! I have added a user story on this in our backlog :)

**Comment by ssorenes** [comment]
We will have an internal meeting on this today @epa095 :) Will keep you updated.

**Comment by GeirArneRodde** [comment]
Planned to be part of minor release 1.5.3 mid february.

**Comment by ssorenes** [comment]
This is now in production.
