### ISSUE TITLE
Add access metadata field for time series data tags

### ISSUE THREAD

**Issue by asmfstatoil** [equinor/OmniaPlant#4]
**Is your feature request related to a problem? Please describe.**
I can use an existing pipeline to transfer time series data from an equinor source system to OmniaPlant Timeseries database, where it will be available for end users based on a different access protection scheme than in the source. Let's call it a privilege escalation bug.

**Describe the solution you'd like**
Time series tag metadata should include an access-group property
System to system pipelines, i.e. those creating tags, should include on access-group metadata to make it possible for Timeseries api to inherit/reproduce data access to it's end-users.

**Describe alternatives you've considered**
Don't allow transfer of data from other equinor source data systems.

**Additional context**

**Comment by GeirArneRodde** [comment]
Hi Åsmund.
Closing the feature request, as it is added tp out internal improvements log (internal ref 13616). Will contact you for further clarfications.
rgds
Geir Arne
